### ISSUE TITLE
/usr/include/thrust/system/detail/generic/memory.inl:40:3: error: invalid application of ‘sizeof’ to incomplete type ‘thrust::detail::STATIC_ASSERTION_FAILURE<false>’    THRUST_STATIC_ASSERT( (thrust::detail::depend_on_instantiation<Size, false>::value) );

### ISSUE THREAD

**Issue by pickou** [wiep/cudaVec#1]
I build your project, and ran into the issue bellow.
```
/usr/include/thrust/system/detail/generic/memory.inl:40:3: error: invalid application of ‘sizeof’ to incomplete type ‘thrust::detail::STATIC_ASSERTION_FAILURE<false>’    THRUST_STATIC_ASSERT( (thrust::detail::depend_on_instantiation<Size, false>::value) );
```
Can you help me out, thank you.

cuda version 8.0， g++ version 4.9.

**Comment by wiep** [comment]
hello, the code and the paper were released in 2011. since its release, the code hasn't been updated. i'm not surprised that the project doesn't compile with a more recent version of cuda or a more recent version thrust. presumably the changes in these libraries would have to be incorporated into the code. i'm sorry that i can't help you.

a link to the paper can be found on the chair's website [1].

[1] https://graphics.tu-bs.de/publications/wiemann2011cuda

**Comment by pickou** [comment]
Thanks!
